name: Build APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  flutter_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build App
        run: |
          flutter pub get
          flutter build apk --profile

      - name: Save File
        uses: actions/upload-artifact@v3
        with:
          name: UngDungLocMau
          path: build/app/outputs/flutter-apk/app-profile.apk
